version: "3.0"

services:
  mongo:
    container_name: ml-mongo
    image: mongo:4.4.6
    volumes:
      - ${MONGO_VOLUME:-./data/db}:/data/db
      - ./mongod.conf:/etc/mongo.conf:ro
    ports:
      - ${MONGO_PORT:-27017}:27017

  mongo-express:
    image: mongo-express:0.54
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    container_name: ml_mongo_express
    ports:
      - ${MONGO_EXPRESS_PORT:-9081}:8081
